dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    version: 0.6.6
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'